# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0003_auto_20170125_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(default='some string', max_length=50),
        ),
    ]
