# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0006_auto_20170125_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
