# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0007_auto_20170125_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='payment_type_name',
            field=models.CharField(choices=[('VISA', 'VISA'), ('MasterCard', 'MasterCard'), ('American Express', 'American Express')], default='none', max_length=16),
        ),
    ]
