# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0013_merge_20170125_1447'),
        ('bangazon_api', '0003_auto_20170125_1939'),
    ]

    operations = [
    ]
