# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0015_auto_20170126_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_2',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
