# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0017_merge_20170126_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='category',
        ),
    ]
